name: Build & Deploy Worker

on:
  push:
    branches:
      - main
    paths:
      - 'src/worker/**'
      - 'src/Dockerfile.worker'
      - '.github/workflows/worker-build-deploy.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'src/worker/**'
      - 'src/Dockerfile.worker'
        
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-worker:
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write

    uses: ./.github/workflows/reusable-containerapp-build-deploy.yml

    with:
      project_path: src/worker/worker.csproj
      dockerfile_path: ./src/Dockerfile.worker
      image_name: worker
      container_app_name: ca-worker-si-dv01
      environment_name: SUB-DV-IPAAS-SI-01

    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}